### ISSUE TITLE
Performance tests failing in the examples

### ISSUE THREAD

**Issue by Philibert92** [dynawo/dyn-grid-compliance-verification#31]
Several simulations are failing in the examples.

The ones I found were the following (but there might be others):

dgcv/examples/PPM/Dynawo/IEC2015 : I10 is failing

![Image](https://github.com/user-attachments/assets/a4a8e17b-9b37-4ece-9a26-70514688f82d)

dgcv/examples/PPM/Dynawo/IEC2020 : I5 and I10 are failing

![Image](https://github.com/user-attachments/assets/85eccfd5-31e5-4af8-976f-edcfb1092c7f)

dgcv/examples/PPM/Dynawo/WECC : I7 and I10 are failing
![Image](https://github.com/user-attachments/assets/e91a5f1c-6f07-4470-9716-0c344e550310)

This might be a problem with the models, the solvers or with dynawo more than with the dgcv tool itself. However, I still think we should work for those examples tests to be fully working.

**Comment by marcosmc** [comment]
Tests I5 and I7 have been fixed.

**Comment by Philibert92** [comment]
[Fiche_I10_Example_IEC_for_Aia_PDRControl.zip](https://github.com/user-attachments/files/26704563/Fiche_I10_Example_IEC_for_Aia_PDRControl.zip)

[Fiche_I10_Example_WECC_for_Aia_PDRControl.zip](https://github.com/user-attachments/files/26704285/Fiche_I10_Example_WECC_for_Aia_PDRControl.zip)

Please find attached 2 test cases for sheet I10, one with a IEC model, the other with a WECC model. You can use this as a model to fix the I10 simulations in DyCoV. This model is working with the 3801_WECC_PCS_rebased branch.

I had to change the following default parameters that are common to all WECC models in DyCoV in order to have a realistic test : 

```
 <par type="DOUBLE" name="photovoltaics_DDn" value="100"/> <!-- Changed value compared to default tuning -->
 <par type="DOUBLE" name="photovoltaics_DUp" value="100"/> <!-- Changed value compared to default tuning -->
 <par type="DOUBLE" name="photovoltaics_FDbd1Pu" value="0.001"/> <!-- Changed value compared to default tuning -->
 <par type="DOUBLE" name="photovoltaics_FDbd2Pu" value="0.001"/> <!-- Changed value compared to default tuning -->
```

For IEC models, It seems the default tuning is already working. 

Please tell me if you need other elements in order to work on this.

**Comment by marcosmc** [comment]
This issue is currently considered dependent on the Dynawo integration (PR #3952).

The underlying initialization problems are expected to be resolved once Dynawo is integrated into `master`, as the initialization sequence will change accordingly.

However, this issue will remain open until the Dynawo integration (PR #3952) is available and the behavior is validated.

**Comment by Philibert92** [comment]
[Simulating with v1.0 and 3801_WECC_PCS_rebased]

I'm not sure the quantities computed by DyCoV are the right one for the I10 simulation.
Please find attached the src/dycov/model_lib/TSO_model/Islanding_2Loads_SynchCond/TSOModel.par file with comments on what some values should be (they appear different from this when I launch test on PV WECCCurrentSource example)

[TSOModel.par.zip](https://github.com/user-attachments/files/27053502/TSOModel.par.zip)

Moreover, once the initial conditions are verified for this test, I suggest to change the following parameters in all WECC examples in order to have more stable simulations : 

```
<par type="DOUBLE" name="photovoltaics_Kig" value="2.36"/> --> change value to 4
<par type="DOUBLE" name="photovoltaics_Kpg" value="0.05"/> --> change value to 1
```

Finally, one should ensure that issue #268 is not applying to the test case being tested. This would make I10 simulation unstable.
.

**Comment by Philibert92** [comment]
[Simulating with v1.0 and 3801_WECC_PCS_rebased]

The IEC models still fail.
At first everything seems okay but ~2.6s after the event power goes to 0 and I don't know why. Maybe there are protections.
@louisg-rte, do you have any idea about what is happening ?

Simulation with example examples/Model/Wind/IECA2020/Dynawo/Zone3 :
<img width="752" height="530" alt="Image" src="https://github.com/user-attachments/assets/ead74082-c07c-4ffc-9982-9c97c294382a" />

**Comment by louisg-rte** [comment]
Indeed the IEC model was tripping due to under frequency protections but this is not the root problem. To correctly perform I10 sheet there need to be a proper OmegaRef model (which cannot be set to constant 1 pu like we do for all the other test cases). OmegaRef should be the speed of the synchronous condenser (because this is the only synchronous machine connected). Otherwise the steady-state after the load connection can't be flat electrical quantities in the phasor domain and the simulation is unstable:

<img width="666" height="479" alt="Image" src="https://github.com/user-attachments/assets/6a920c2e-8034-4f67-8fb7-c7b11b7c9d72" />

To do that please use the attached Omega.par and Omega.dyd files for all the I10 test cases (this is not specifically related to IEC models, this should be use for every models)

[Omega.zip](https://github.com/user-attachments/files/27119328/Omega.zip)

**Comment by louisg-rte** [comment]
As discussed today, we should implement the Omega model given in the last comment (Omega.zip attachment) for all the I10 test cases. After that, the test case should run ok with all the models and the issue could be closed. 

There may be some difficulties with this test cases but this will be "physical" problems (badly damped oscillations for example) but this is not directly related to DyCoV.

@marcosmc

**Comment by marcosmc** [comment]
All example simulations are now running successfully after the fixes applied (including the proper OmegaRef modeling for I10 cases).

The remaining issues are related to stability (e.g. oscillations, non-flat steady-state behavior), which are not simulation failures but physical/model-related aspects.

These are now tracked in a separate issue #319 

Closing this issue.
